Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc_week4849.Models;
using mvc_week4849.Models.Services;
using mvc_week4849.Models.ViewModels;

namespace mvc_week4849.Controllers
{
    public class CitiesController : Controller
    {
        private ICountriesService _countriesService;
        private ICitiesService _citiesService;
        private IPeopleService _peopleService;


        public CitiesController(ICountriesService countriesService, ICitiesService citiesService, IPeopleService peopleService)
        {
            _countriesService = countriesService;
            _citiesService = citiesService;
            _peopleService = peopleService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            CitiesViewModel citiesViewModel = _citiesService.All();
            citiesViewModel.PeopleList = _peopleService.All().PeopleList;
            citiesViewModel.CountriesList = _countriesService.All().CountriesList;

            return View(citiesViewModel);
        }

        [HttpPost]
        public IActionResult Filter(CitiesViewModel searchTerm)
        {
            CitiesViewModel citiesViewModel = _citiesService.FindBy(searchTerm);
            citiesViewModel.CountriesList = _countriesService.All().CountriesList;
            citiesViewModel.PeopleList = _peopleService.All().PeopleList;

            return View("Index", citiesViewModel);
        }

        [HttpPost]
        public IActionResult Create(CitiesViewModel citiesViewModel)
        {
            if (ModelState.IsValid)
            {
                _citiesService.Add(citiesViewModel.CreateCity);

                return RedirectToAction(nameof(Index));
            }


            return View("Index", _citiesService.All());
        }

        public IActionResult Delete(int id)
        {
            if (_citiesService.Remove(id))
            {
                ViewBag.msg = "The post was deleted";
            }
            else
            {
                ViewBag.msg = "Unable to delete the post";
            }
            CitiesViewModel citiesViewModel = _citiesService.All();
            citiesViewModel.CountriesList = _countriesService.All().CountriesList;
            return View("Index", citiesViewModel);
        }
    }
}

Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc_week4849.Models;
using mvc_week4849.Models.Services;
using mvc_week4849.Models.ViewModels;

namespace mvc_week4849.Controllers
{
    public class CountriesController : Controller
    {

        private ICountriesService _countriesService;
        private ICitiesService _citiesService;

        public CountriesController(ICountriesService countriesService, ICitiesService citiesService)
        {
            _countriesService = countriesService;
            _citiesService = citiesService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            CountriesViewModel countriesViewModel = _countriesService.All();
            countriesViewModel.CitiesList = _citiesService.All().CitiesList;

            return View(countriesViewModel);
        }


        [HttpPost]
        public IActionResult Filter(CountriesViewModel searchTerm)
        {
            CountriesViewModel countriesViewModel = _countriesService.FindBy(searchTerm);
            countriesViewModel.CitiesList = _citiesService.All().CitiesList;
            return View("Index", countriesViewModel);
        }

        [HttpPost]
        public IActionResult Create(CountriesViewModel countriesViewModel)
        {
            if (ModelState.IsValid)
            {
                _countriesService.Add(countriesViewModel.CreateCountry);

                return RedirectToAction(nameof(Index));
            }
            return View("Index", _countriesService.All());
        }

        public IActionResult Delete(int id)
        {
            if (_countriesService.Remove(id))
            {
                ViewBag.msg = "The post was deleted";
            }
            else
            {
                ViewBag.msg = "Unable to delete the post";
            }
            CountriesViewModel countriesViewModel = _countriesService.All();
            countriesViewModel.CitiesList = _citiesService.All().CitiesList;
            return View("Index", countriesViewModel);
        }
    }
}

Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc_week4849.Models.Services;
using mvc_week4849.Models.ViewModels;

namespace mvc_week4849.Controllers
{
    public class LanguagesController : Controller
    {
        private ILanguagesService _languagesService;
        private ICitiesService _citiesService;
        private IPeopleService _peopleService;


        public LanguagesController(ILanguagesService languagesService, ICitiesService citiesService, IPeopleService peopleService)
        {
            _languagesService = languagesService;
            _citiesService = citiesService;
            _peopleService = peopleService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            LanguagesViewModel languagesViewModel = _languagesService.All();
            languagesViewModel.PeopleList = _peopleService.All().PeopleList;

            return View(languagesViewModel);
        }


        [HttpPost]
        public IActionResult Filter(LanguagesViewModel searchTerm)
        {
            return View("Index", _languagesService.FindBy(searchTerm));
        }



        [HttpPost]
        public IActionResult Create(LanguagesViewModel languagesViewModel)
        {
            if (ModelState.IsValid)
            {
                _languagesService.Add(languagesViewModel.CreateLanguage);

                return RedirectToAction(nameof(Index));
            }
            return View("Index", _languagesService.All());
        }

        public IActionResult Delete(int id)
        {
            if (_languagesService.Remove(id))
            {
                ViewBag.msg = "The post was deleted";
            }
            else
            {
                ViewBag.msg = "Unable to delete the post";
            }
            LanguagesViewModel languagesViewModel = _languagesService.All();
            languagesViewModel.PeopleList = _peopleService.All().PeopleList;
            return View("Index", languagesViewModel);
        }
    }
}

Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using mvc_week4849.Models;
using mvc_week4849.Models.Services;
using mvc_week4849.Models.ViewModels;

namespace mvc_week4849.Controllers
{
    public class PeopleController : Controller
    {
        private IPeopleService _peopleService;
        private ICitiesService _citiesService;
        private ILanguagesService _languagesService;

        public PeopleController(IPeopleService peopleService, ICitiesService citiesService, ILanguagesService languagesService)
        {
            _peopleService = peopleService;
            _citiesService = citiesService;
            _languagesService = languagesService;
        }

        [HttpGet]
        public IActionResult Index()
        {

            PeopleViewModel peopleViewModel = _peopleService.All();
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View(peopleViewModel);
        }
     
        [HttpPost]
        public IActionResult Filter(PeopleViewModel filtered)
        {
            PeopleViewModel peopleViewModel = _peopleService.FindBy(filtered);
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View("Index", peopleViewModel);
        }
 
        [HttpPost]
        public IActionResult Create(PeopleViewModel newPerson)
        {           
           if (ModelState.IsValid)
           {
               _peopleService.Add(newPerson.CreatePerson);

               return RedirectToAction(nameof(Index));
           }

            PeopleViewModel peopleViewModel = _peopleService.All();
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View("Index", peopleViewModel); 
        }
     
       public IActionResult Delete(int id)
       {
            if (_peopleService.Remove(id))
            {
                ViewBag.msg = "The post was deleted";
            }
            else
            {
                ViewBag.msg = "Unable to delete the post";
            }

            PeopleViewModel peopleViewModel = _peopleService.All();
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View("Index", peopleViewModel);
       }
      
       [HttpGet]
       public IActionResult Partialview()
       {
            PeopleViewModel peopleViewModel = _peopleService.All();
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View(peopleViewModel);
        }

       [HttpPost]
       public IActionResult CreatePartial(PeopleViewModel newPerson)
          {
          if (ModelState.IsValid)
          {
              _peopleService.Add(newPerson.CreatePerson);

              return RedirectToAction(nameof(Partialview));
          }

            PeopleViewModel peopleViewModel = _peopleService.All();
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View("Partialview", peopleViewModel);
       }
      
       [HttpPost]
       public IActionResult FilterPartial(PeopleViewModel filtered)
       {
            PeopleViewModel peopleViewModel = _peopleService.FindBy(filtered);
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View("Partialview", peopleViewModel);
       }
       
       public IActionResult DeletePartial(int id)
       {
            if(_peopleService.Remove(id))
            {
                ViewBag.msg = "The post was deleted";
            }
            else
            {
                ViewBag.msg = "Unable to delete the post";
            }

            PeopleViewModel peopleViewModel = _peopleService.All();
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View("Partialview", peopleViewModel);
        }
       
       [HttpGet]
       public IActionResult Ajax()
       {    
            PeopleViewModel peopleViewModel = _peopleService.All();
            peopleViewModel.CitiesList = _citiesService.All().CitiesList;
            peopleViewModel.LanguagesList = _languagesService.All().LanguagesList;

            return View(peopleViewModel);          
       }

       [HttpGet]
       public IActionResult CreateForm()
       {
          return PartialView("_CreatePeopleAjaxPartialView");
       }

       [HttpPost]
       public IActionResult FilterAjax(PeopleViewModel peopleViewModel)
       {
           return View("Ajax", _peopleService.FindBy(peopleViewModel));
       }
                  
       [HttpPost]
       public IActionResult AjaxDeletePartial(int id)
       {
           if (_peopleService.Remove(id))
           {
               return Ok("The post was deleted");
           }
           else
           {
               return NotFound("Unable to delete the post");
           }        
       }
       
       [HttpGet]
       public IActionResult AjaxEditPost(int id)
       {
            PeopleViewModel peopleViewModel = new PeopleViewModel()
            {
                EditedPerson = _peopleService.FindBy(id),
                CitiesList = _citiesService.All().CitiesList
            };        
           
           return PartialView("_EditPeopleAjaxPartialView", peopleViewModel);
       }

       [HttpPost]
       public IActionResult AjaxEditPost(Person person)
       {
           CreatePersonViewModel personToEdit = new CreatePersonViewModel()

           {
               PersonName = person.PersonName,
               PhoneNumber = person.PhoneNumber,
               CityId = person.City.Id
           };
           if (TryValidateModel(personToEdit))
           {              
               return PartialView("_PeopleAjaxStrippedPartialView", _peopleService.Edit(person.Id, person));
           }
           else
           {
               return PartialView("_PeopleAjaxStrippedPartialView", _peopleService.FindBy(person.Id));
           }
       }
       
       [HttpPost]
       public IActionResult CreateAjax(CreatePersonViewModel createPersonViewModel)
       {
           if (ModelState.IsValid)
           {
               Person person = _peopleService.Add(createPersonViewModel);

               return PartialView("_PeopleAjaxPartialView", person);
           }
           else
           {
               return PartialView("_CreatePeopleAjaxPartialView", createPersonViewModel);
           }
       }     
    }
}

Views/Shared/_CreatePeopleAjaxPartialView.cshtml
@model PeopleViewModel


<form asp-controller="People" asp-action="CreateAjax" onsubmit="CreatePerson(event, this); return false;">

    <label asp-for="CreatePerson.PersonName"></label>
    <input asp-for="CreatePerson.PersonName" />
    <span asp-validation-for="CreatePerson.PersonName"></span>

    <label asp-for="CreatePerson.PhoneNumber"></label>
    <input asp-for="CreatePerson.PhoneNumber" />
    <span asp-validation-for="CreatePerson.PhoneNumber"></span>

    <label asp-for="CreatePerson.CityId"></label>
    <select asp-for="CreatePerson.CityId">
        @foreach (var item in Model.CitiesList)
        {
            <option value="@item.Id">@item.CityName</option>           
        }
    </select>
    <span asp-validation-for="CreatePerson.CityId"></span>

    <input class="btn btn-primary" type="submit" value="Register person" />

</form>

Views/Shared/_EditPeopleAjaxPartialView.cshtml
@model PeopleViewModel


<form asp-controller="People" asp-action="AjaxEditPost" onsubmit="PostEditedEntry(@Model.EditedPerson.Id, event, this)">

    <label asp-for="EditedPerson.PersonName"></label>
    <input asp-for="EditedPerson.PersonName" value="@Model.EditedPerson.PersonName" />
    <span asp-validation-for="EditedPerson.PersonName"></span>

    <label asp-for="EditedPerson.PhoneNumber"></label>
    <input asp-for="EditedPerson.PhoneNumber" value="@Model.EditedPerson.PhoneNumber" />
    <span asp-validation-for="EditedPerson.PhoneNumber"></span>

    <label asp-for="EditedPerson.City.Id"></label>
    <select asp-for="EditedPerson.City.Id">
        @foreach (var item in Model.CitiesList)
        {
            if (item.CityName == Model.EditedPerson.City.CityName)
            {
                <option value="@item.Id" selected>@item.CityName</option>
            }
            else
            {
                <option value="@item.Id">@item.CityName</option>
            }
        }
    </select>
    <span asp-validation-for="CreatePerson.CityId"></span>

    <label asp-for="EditedPerson.PersonLanguages"></label>
    <select asp-for="EditedPerson.PersonLanguages">
        @foreach (var item in Model.LanguagesList)
        {
            <option value="@item.Id">@item.LanguageName</option>
        }
    </select>
    <span asp-validation-for="EditedPerson.PersonLanguages"></span>


    <input class="btn btn-primary" type="submit" value="Edit post" />
    <input class="btn btn-outline-primary" type="button" value="Cancel" />

</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_week4849</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc_week4849</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People_List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Partialview">People_List_Partial_View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Ajax">People_List_Ajax</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Languages" asp-action="Index">Languages</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - mvc_week4849
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/PeopleAjax.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PeopleAjaxPartialView.cshtml
@model Person

<div id="personId-@Model.Id" class="row">
    <div class="col">
        <p>@Model.PersonName</p>
    </div>
    <div class="col">
        <p>@Model.PhoneNumber</p>
    </div>
    <div class="col">
        <p>@Model.City.CityName</p>
    </div>
    @if (@Model.PersonLanguages.Count > 0)
    {
        <div class="col">
            @foreach (var language in @Model.PersonLanguages)
            {
                @language.Language.LanguageName @:<br />
            }
            </div>
        }
        else
        {
            <div class="col"></div>
    }
    <div class="col">
        <a class="btn btn-warning" onclick="EditEntryForm('@Model.Id')">Edit</a>
        <a class="btn btn-danger" asp-action="AjaxDeletePartial" asp-controller="People" onclick="Delete('@Model.Id', event, this); return false;">Delete</a>
    </div>
</div>

Views/Shared/_PeopleAjaxStrippedPartialView.cshtml
@model Person

<div class="col">
        <p>@Model.PersonName</p>
    </div>
    <div class="col">
        <p>@Model.PhoneNumber</p>
    </div>
    <div class="col">
        <p>@Model.City</p>
    </div>
    <div class="col">
        <a class="btn btn-warning" onclick="EditEntryForm('@Model.Id')">Edit</a>
        <a class="btn btn-danger" asp-action="AjaxDeletePartial" asp-controller="People" onclick="Delete('@Model.Id', event, this); return false;">Delete</a>
</div>

Views/Shared/_PeopleAjaxView.cshtml
@model Person

<div class="row">
    <div class="col">
        <p>@Model.PersonName</p>
    </div>
    <div class="col">
        <p>@Model.PhoneNumber</p>
    </div>
    <div class="col">
        <p>@Model.City</p>
    </div>
    <div class="col">
        <a class="btn btn-danger" asp-action="AjaxDeletePartial" asp-controller="People" asp-route-id="@Model.Id">Delete</a>
    </div>
</div>

Views/Shared/_PeoplePartialView.cshtml
@model Person

<div class="row">
    <div class="col">
        <p>@Model.PersonName</p>
    </div>
    <div class="col">
        <p>@Model.PhoneNumber</p>
    </div>
    <div class="col">
        <p>@Model.City.CityName</p>
    </div>
    <div class="col">
        <a class="btn btn-danger" asp-action="DeletePartial" asp-controller="People" asp-route-id="@Model.Id">Delete</a>
    </div>
</div>